"""Premise ORM — persists a non-obvious solution hypothesis generated by the agent.

Invariants:
    - Always belongs to a Round and a Session
    - score is nullable (set when user scores)
    - is_winner defaults to False (set on "Problem Resolved")
    - premise_type is one of: initial, conservative, radical, combination

Design Decisions:
    - session_id denormalized: allows querying premises by session without joining Round
      (ADR: query performance for get_negative_context and query_premises)
"""

import uuid
from datetime import datetime, timezone

from sqlalchemy import String, Text, Float, Boolean, DateTime, ForeignKey
from sqlalchemy.orm import Mapped, mapped_column, relationship
from sqlalchemy.dialects.postgresql import UUID

from app.db.base import Base


class Premise(Base):
    """Premise entity — a non-obvious solution hypothesis."""
    __tablename__ = "premises"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4,
    )
    round_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("rounds.id"), nullable=False,
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("sessions.id"), nullable=False,
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    body: Mapped[str | None] = mapped_column(Text, nullable=True)
    premise_type: Mapped[str] = mapped_column(
        String(20), nullable=False, default="initial",
    )
    score: Mapped[float | None] = mapped_column(Float, nullable=True)
    user_comment: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_winner: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False,
    )
    violated_axiom: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
    )
    cross_domain_source: Mapped[str | None] = mapped_column(
        String(500), nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
    )

    round: Mapped["Round"] = relationship(
        "Round", back_populates="premises",
    )
