"""Crystallize Handlers — Phase 6 tool implementation (1 method).

Invariants:
    - Generates a 10-section Knowledge Document in Markdown
    - Saves to /tmp/ghostpath/specs/{session_id}.md
    - Pauses agent loop (awaiting_user_input = True)

Design Decisions:
    - Agent provides all 10 sections as tool input — not auto-generated from DB
    - This ensures the agent's reasoning chain is captured in the document
"""

import os
import tempfile

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.forge_state import ForgeState


class CrystallizeHandlers:
    """Phase 6: CRYSTALLIZE — generate final Knowledge Document."""

    def __init__(self, db: AsyncSession, state: ForgeState):
        self.db = db
        self.state = state

    async def generate_knowledge_document(
        self, session: object, input_data: dict,
    ) -> dict:
        """Produce final 10-section Knowledge Document."""
        title = input_data.get("title", "Knowledge Document")
        sections = {
            "executive_summary": input_data.get("executive_summary", ""),
            "problem_analysis": input_data.get("problem_analysis", ""),
            "methodology": input_data.get("methodology", ""),
            "key_discoveries": input_data.get("key_discoveries", ""),
            "knowledge_claims": input_data.get("knowledge_claims", ""),
            "knowledge_graph_description": input_data.get("knowledge_graph_description", ""),
            "rejected_paths": input_data.get("rejected_paths", ""),
            "implementation_implications": input_data.get("implementation_implications", ""),
            "open_questions": input_data.get("open_questions", ""),
            "evolutionary_journey": input_data.get("evolutionary_journey", ""),
        }

        markdown = _build_markdown(title, sections)

        # Save to filesystem (cross-platform temp dir)
        specs_dir = os.path.join(tempfile.gettempdir(), "o-edger", "specs")
        os.makedirs(specs_dir, exist_ok=True)
        spec_path = os.path.join(specs_dir, f"{session.id}.md")
        with open(spec_path, "w", encoding="utf-8") as f:
            f.write(markdown)

        # Store markdown in ForgeState for SSE delivery
        self.state.knowledge_document_markdown = markdown

        # Pause agent loop
        self.state.awaiting_user_input = True
        self.state.awaiting_input_type = "knowledge_document"

        return {
            "status": "ok",
            "title": title,
            "spec_path": spec_path,
            "markdown": markdown,
            "paused": True,
        }


def _build_markdown(title: str, sections: dict) -> str:
    """Build the 10-section Knowledge Document markdown."""
    parts = [
        f"# {title}",
        "",
        "## 1. Executive Summary",
        sections["executive_summary"],
        "",
        "## 2. Problem Analysis",
        sections["problem_analysis"],
        "",
        "## 3. Methodology",
        sections["methodology"],
        "",
        "## 4. Key Discoveries",
        sections["key_discoveries"],
        "",
        "## 5. Knowledge Claims",
        sections["knowledge_claims"],
        "",
        "## 6. Knowledge Graph",
        sections["knowledge_graph_description"],
        "",
        "## 7. Rejected Paths (Negative Knowledge)",
        sections["rejected_paths"],
        "",
        "## 8. Implementation Implications",
        sections["implementation_implications"],
        "",
        "## 9. Open Questions",
        sections["open_questions"],
        "",
        "## 10. Evolutionary Journey",
        sections["evolutionary_journey"],
        "",
        "---",
        "*Generated by O-Edger Knowledge Creation Engine*",
    ]
    return "\n\n".join(parts)
