"""Crystallize Handlers — Phase 6 tool implementation (1 method).

Invariants:
    - Assembles final Knowledge Document from working document sections
    - Saves to /tmp/triz/specs/{session_id}.md
    - Pauses agent loop (awaiting_user_input = True)

Design Decisions:
    - Working document built incrementally across phases 1-5
    - Handler reads from ForgeState.working_document (not tool input)
    - Missing sections show placeholder text (not an error)
"""

import os
import tempfile

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.forge_state import ForgeState
from app.core.repository_protocols import SessionLike


_SECTION_ORDER = [
    ("core_insight", "1. The Discovery"),
    ("problem_context", "2. Why This Matters"),
    ("reasoning_chain", "3. Reasoning Chain"),
    ("evidence_base", "4. Evidence Base"),
    ("technical_details", "5. Technical Specification"),
    ("cross_domain_patterns", "6. Cross-Domain Connections"),
    ("boundaries", "7. Boundaries & Limitations"),
    ("implementation_guide", "8. Implementation Guide"),
    ("next_frontiers", "9. Open Frontiers"),
]


def _build_markdown(title: str, working_doc: dict[str, str]) -> str:
    """Build the 9-section Knowledge Document from working document."""
    parts = [f"# {title}", ""]
    for key, heading in _SECTION_ORDER:
        content = working_doc.get(key, "_[Section not yet written]_")
        parts.extend([f"## {heading}", "", content, ""])
    parts.extend(["---", "*Generated by TRIZ Knowledge Creation Engine*"])
    return "\n\n".join(parts)


class CrystallizeHandlers:
    """Phase 6: CRYSTALLIZE — assemble final Knowledge Document."""

    def __init__(self, db: AsyncSession, state: ForgeState):
        self.db = db
        self.state = state

    async def generate_knowledge_document(
        self, session: SessionLike, input_data: dict,
    ) -> dict:
        """Assemble final Knowledge Document from working sections."""
        title = input_data.get("title", "Knowledge Document")
        markdown = _build_markdown(title, self.state.working_document)

        # Save to filesystem (cross-platform temp dir)
        specs_dir = os.path.join(tempfile.gettempdir(), "triz", "specs")
        os.makedirs(specs_dir, exist_ok=True)
        spec_path = os.path.join(specs_dir, f"{session.id}.md")
        with open(spec_path, "w", encoding="utf-8") as f:
            f.write(markdown)

        # Store markdown in ForgeState for SSE delivery
        self.state.knowledge_document_markdown = markdown

        # Pause agent loop
        self.state.awaiting_user_input = True
        self.state.awaiting_input_type = "knowledge_document"

        return {
            "status": "ok",
            "title": title,
            "spec_path": spec_path,
            "markdown": markdown,
            "paused": True,
        }
