"""Rename starred → resonated on cross_domain_analogies.

Revision ID: 008_rename_starred_to_resonated
Revises: 007_add_cache_token_counters
Create Date: 2026-02-16

ADR: 'starred' was the old binary star-toggle UX. The current UX presents
resonance options (4 choices generated by the agent). Renaming the column
to 'resonated' aligns the DB schema with the actual interaction model.
"""
from typing import Sequence, Union

from alembic import op

# revision identifiers
revision: str = "008_rename_starred_to_resonated"
down_revision: Union[str, None] = "007_add_cache_token_counters"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.alter_column(
        "cross_domain_analogies", "starred",
        new_column_name="resonated",
    )


def downgrade() -> None:
    op.alter_column(
        "cross_domain_analogies", "resonated",
        new_column_name="starred",
    )
